import React from 'react';
import Head from 'next/head';
import { Card } from 'flowbite-react';
import Footer from '../components/Footer';
import styles from '../styles/About.module.css';
import navStyles from '../styles/Navbar.module.css';

const about = () => (
  <div>
    <Head>
      <title>HireMe | About</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/HireMeHead.png" />
    </Head>
    <main>
      <Card className={styles.aboutContainer}>
        <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
          Tech Stack used:
        </h5>
        <ul className="list-disc pl-5 text-gray-500 dark:text-gray-400">
          <li>Next.JS 13</li>
          <li>Google authentication</li>
          <li>Google Map API</li>
          <li>Spring Boot</li>
          <li>MongoDB</li>
          <li>Deployed to Azure</li>
        </ul>
        <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
          How we could further develop the app:
        </h5>
        <ul className="list-disc pl-5 text-gray-500 dark:text-gray-400">
          <li>Add calendar functionality</li>
          <li>Add chat functionality between user and professional</li>
          <li>Add payment functionality</li>
        </ul>
      </Card>
      <Footer />
    </main>
  </div>

);
export default about;
