import React from 'react';
import Head from 'next/head';
import {
  Card, Navbar, Dropdown, Avatar,
} from 'flowbite-react';
import { signIn, useSession, signOut } from 'next-auth/react';
import Link from 'next/link';
import Footer from '../components/Footer';
import styles from '../styles/About.module.css';
import navStyles from '../styles/Navbar.module.css';

const About = () => {
  const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>HireMe | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/HireMeHead.png" />
      </Head>
      <main className={styles.about}>
        <Card className={styles.aboutContainer}>
          <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Tech Stack used:
          </h5>
          <ul className="list-disc pl-5 text-gray-500 dark:text-gray-400">
            <li>Next.JS 13</li>
            <li>Google authentication</li>
            <li>Google Map API</li>
            <li>Spring Boot</li>
            <li>MongoDB</li>
            <li>Deployed to Azure</li>
          </ul>
          <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            How we could further develop the app:
          </h5>
          <ul className="list-disc pl-5 text-gray-500 dark:text-gray-400">
            <li>Add calendar functionality</li>
            <li>Add chat functionality between user and professional</li>
            <li>Add payment functionality</li>
          </ul>
        </Card>
      </main>
      <nav className={navStyles.bottomNav}>
        <div className={navStyles.bottomNavLinks}>
          <Navbar.Link
            href="/">
            Home
          </Navbar.Link>
          <Navbar.Link href="/about">
            About
          </Navbar.Link>
          <Navbar.Link href="/contact">
            Contact
          </Navbar.Link>
        </div>
        <div className={navStyles.bottomNavProfile}>
          {session ? (
            <div className="flex md:order-2">
              <Dropdown
                arrowIcon={false}
                inline
                label={<Avatar alt="User settings" img={session.user.image} rounded />}>
                <Dropdown.Header>
                  <span className="block text-sm">
                    {session.user.name}
                  </span>
                  <span className="block truncate text-sm font-medium">
                    {session.user.email}
                  </span>
                </Dropdown.Header>
                <Dropdown.Item>
                  <Link href="/account">My Account</Link>
                </Dropdown.Item>
                <Dropdown.Divider />
                <Dropdown.Item onClick={() => signOut()}>
                  Sign out
                </Dropdown.Item>
              </Dropdown>
            </div>
          ) : <Link href="/login" onClick={() => signIn()}>Login</Link>}
        </div>
      </nav>
      <div className={navStyles.bottomFooter}>
        <Footer />
      </div>
    </div>

  );
};
export default About;
