import React from 'react';
import Head from 'next/head';
import { Card } from 'flowbite-react';
import Link from 'next/link';
import Footer from '../components/Footer';
import styles from '../styles/Contact.module.css';

const contact = () => (
  <div>
    <Head>
      <title>HireMe | Contact Us</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/HireMeHead.png" />
    </Head>
    <main className={styles.mainContainer}>
      <h1>Contact us</h1>

      <div className="max-w-sm">
        <Card className={styles.contact1} imgSrc="https://media-exp1.licdn.com/dms/image/C5603AQGLGCfNb53Zig/profile-displayphoto-shrink_800_800/0/1658348060874?e=1675296000&v=beta&t=bUILGMhJzPwgM0ZhauOl94a04yWQsqJ3IiV5d4f-On4">
          <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Shalihin Ahmad Mohamad
          </h5>
          <p>
            {' '}
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Suscipit qui et aliquid vel soluta eum veniam.
            Consequatur nam recusandae magni reiciendis,
            minus sed quas repudiandae ad aspernatur repellat perspiciatis saepe.
            {' '}

          </p>
          <p className="font-normal text-gray-700 dark:text-gray-400">
            Java Fullstack Developer
            {' '}
            <br />
            Mohamad.Ahmad@appliedtechnology.se
            <Link href="https://www.linkedin.com/in/arielshaka"> Shas LinkedIn</Link>
            {' '}
            <br />
            <Link href="https://github.com/ArielShaka">Sha Github</Link>
          </p>
        </Card>

        <Card className={styles.contact2} imgSrc="https://scontent.farn1-2.fna.fbcdn.net/v/t39.30808-6/274647233_2307270672744153_7557777654622178884_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=174925&_nc_ohc=IbmFPu-ybeAAX9M5Vgl&_nc_ht=scontent.farn1-2.fna&oh=00_AfDN4n92szvdXZV69g2mtC_nnv2eMk3Qufdhpau1q6DLFw&oe=6388064B">
          <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Ariel Shaka
          </h5>
          <p>
            {' '}
            I'm a very curious person,
            passionate about technologie
            in general and problem solving.
            I find satisafaction in
            building products that would
            have a positive impact on peoples life.
            {' '}
          </p>
          <p className="font-normal text-gray-700 dark:text-gray-400">
            Java Fullstack Developer
            {' '}
            <br />
            ariel.yumembudi@appliedtechnology.se
            <Link href="https://www.linkedin.com/in/arielshaka"> LinkedIn</Link>
            {' '}
            <br />
            <Link href="https://github.com/ArielShaka">Github</Link>
          </p>
        </Card>

        <Card className={styles.contact3} imgSrc="https://media-exp1.licdn.com/dms/image/C4E03AQFda19mTGr7mA/profile-displayphoto-shrink_800_800/0/1629196222496?e=1675296000&v=beta&t=OfddcP89OxBLvikIioVlrnrCKSyPPID4kzPcM_OD6rs">
          <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Filipe Forssblad
          </h5>
          <p>
            {' '}
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Suscipit qui et aliquid vel soluta eum veniam.
            Consequatur nam recusandae magni reiciendis,
            minus sed quas repudiandae ad aspernatur repellat perspiciatis saepe.
            {' '}
          </p>
          <p className="font-normal text-gray-700 dark:text-gray-400">
            Java Fullstack Developer
            {' '}
            <br />
            Filipe.Forssblad@appliedtechnology.se
            <Link href="https://www.linkedin.com/in/arielshaka"> Filipes LinkedIn</Link>
            {' '}
            <br />
            <Link href="https://github.com/ArielShaka">Fil Github</Link>
            {' '}
            <br />
            And he loves titties.
          </p>
        </Card>
      </div>
    </main>
    <Footer />
  </div>
);

export default contact;
