import React from 'react';
import Head from 'next/head';
import { Card } from 'flowbite-react';
import Link from 'next/link';
import Footer from '../components/Footer';
import styles from '../styles/Contact.module.css';

const contact = () => (
  <div>
    <Head>
      <title>HireMe | Contact Us</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/HireMeHead.png" />
    </Head>

    <main>
      <div className="flex flex-row flex-wrap justify-center">
        <div className={styles.contact}>
          <Card imgSrc="shalihin.jpeg">
            <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
              Shalihin Ahmad
            </h5>
            <p>
              {' '}
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Suscipit qui et aliquid vel soluta eum veniam.
              Consequatur nam recusandae magni reiciendis,
              minus sed quas repudiandae ad aspernatur repellat perspiciatis saepe.
              {' '}

            </p>
            <p className="font-normal text-gray-700 dark:text-gray-400">
              Java Fullstack Developer
              {' '}
              <br />
              Mohamad.Ahmad@appliedtechnology.se
              <Link href="https://www.linkedin.com/in/arielshaka"> Shas LinkedIn</Link>
              {' '}
              <br />
              <Link href="https://github.com/ArielShaka">Sha Github</Link>
            </p>
          </Card>
        </div>

        <div className={styles.contact}>
          <Card imgSrc="ariel.jpeg">
            <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
              Ariel Shaka
            </h5>
            <p>
              {' '}
              I'm a very curious person,
              passionate about technologie
              in general and problem solving.
              I find satisafaction in
              building products that would
              have a positive impact on peoples life.
              {' '}
            </p>
            <p className="font-normal text-gray-700 dark:text-gray-400">
              Java Fullstack Developer
              {' '}
              <br />
              ariel.yumembudi@appliedtechnology.se
              <Link href="https://www.linkedin.com/in/arielshaka"> LinkedIn</Link>
              {' '}
              <br />
              <Link href="https://github.com/ArielShaka">Github</Link>
            </p>
          </Card>
        </div>

        <div className={styles.contact}>
          <Card imgSrc="filipe.jpeg">
            <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
              Filipe Forssblad
            </h5>
            <p>
              {' '}
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Suscipit qui et aliquid vel soluta eum veniam.
              Consequatur nam recusandae magni reiciendis,
              minus sed quas repudiandae ad aspernatur repellat perspiciatis saepe.
              {' '}
            </p>
            <p className="font-normal text-gray-700 dark:text-gray-400">
              Java Fullstack Developer
              {' '}
              <br />
              Filipe.Forssblad@appliedtechnology.se
              <Link href="https://www.linkedin.com/in/arielshaka"> Filipes LinkedIn</Link>
              {' '}
              <br />
              <Link href="https://github.com/ArielShaka">Fil Github</Link>
              {' '}
              <br />
              And he loves titties.
            </p>
          </Card>
        </div>
      </div>
    </main>

    <Footer />
  </div>
);

export default contact;
