/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Image from 'next/image';
import Footer from '../components/Footer';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HireMe | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/HireMeHead.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to
          {' '}
          <a href="https://nextjs.org">Hire Me</a>
        </h1>

        <div className={styles.description}>
          <h2>
            {/* An intersection between your needs and their skills
            {' '}
            <br /> */}
            Skilled professionals at your fingertips
            {' '}
            {/* <br />
            Your needs...their skills */}
          </h2>
        </div>
        <Image src="/landingImage.jpeg" alt="landing" width={800} height={800} />

      </main>
      <Footer />
    </div>
  );
}
