/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Footer from '../components/Footer';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HireMe | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/HireMeHead.png" />
      </Head>

      <main className={styles.main}>
        <img src="https://www.lewispies.co.uk/wp-content/uploads/2020/08/web-top-jobs10-tzr-780x501-1.jpg" alt="landing-page" />
        An intersection between your needs and their skills
        {' '}
        <br />
        Skilled professionals at your fingertips
        {' '}
        <br />
        Your needs...their skills

      </main>
      <Footer />
    </div>
  );
}
