/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Footer from '../components/Footer';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HireMe | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="https://5.imimg.com/data5/HJ/PG/MY-26549812/multi-skilled-technician-28mst-29-for-school-500x500.jpg" alt="landing-page" />
        An intersection between your needs and their skills
        {' '}
        <br />
        Skilled professionals at your fingertips
        {' '}
        <br />
        Your needs...their skills

      </main>
      <Footer />
    </div>
  );
}
