import React, { useEffect } from 'react';
import { signIn } from 'next-auth/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Image from 'next/image';
import { Button } from 'flowbite-react';
import Footer from '../components/Footer';

const Login = () => {
  // const { data: session } = useSession();
  const router = useRouter();

  useEffect(() => {
    router.push('/account');
  }, []);

  // if (session) {
  //   return (
  //     <div>
  //       <p>
  //         Welcome,
  //         {session.user.name}
  //       </p>
  //       <button type="submit" onClick={() => signOut()}>Sign out</button>
  //     </div>
  //   );
  // }
  return (
    // <div>
    //   <Head>
    //     <title>HireMe | Login</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/HireMeHead.png" />
    //   </Head>
    //   <p>You are not signed in</p>
    //   <button type="submit" onClick={() => signIn()}>Sign in</button>
    // </div>
    <>
      <Head>
        <title>HireMe | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/HireMeHead.png" />
      </Head>
      <main className="bg-gray-50 dark:bg-gray-900 login-main-container">
        <div className="login-main-container-div flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0 align-middle self-center">
          <Image src="/HireMe.jpg" className="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white" width={300} height={300} alt="company logo" />
          <div className="w-0.5 bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
            <div className="flex flex-col p-6 space-y-4 md:space-y-6 sm:p-8">
              <h1 className="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                Welcome back
              </h1>
              <Button type="submit" onClick={() => signIn()} color="gray">
                <Image src="/google.png" height={20} width={20} alt="google-sign-in" />
                <h2>Log in with Google</h2>
              </Button>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default Login;
